name: Fetch Duolingo Promotion Status (Python)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch-promotion-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and parse API response
        run: |
          import requests
          import re
          import os

          url = "https://duolingo-leaderboards-prod.duolingo.com/leaderboards/7d9f5dd1-8423-491a-91f2-2532052038ce/users/1040196921"
          response = requests.get(url)
          content = response.text
          
          match = re.search(r'"is_promoted":\s*(true|false)', content)
          is_promoted = match.group(1) if match else "null"
          
          print(f"Is promoted: {is_promoted}")
          
          with open(os.environ['GITHUB_ENV'], 'a') as env_file:
              env_file.write(f"IS_PROMOTED={is_promoted}\n")
        shell: python

      - name: Use the result
        run: |
          if [ "${{ env.IS_PROMOTED }}" = "true" ]; then
            echo "User is promoted!"
          elif [ "${{ env.IS_PROMOTED }}" = "false" ]; then
            echo "User is not promoted."
          else
            echo "Could not determine promotion status."
          fi
